#!/bin/bash
set -eu
#set -eux

#YouTube 360p
#18
#YouTube 480p
#135+140
#YouTube 720p
#136+140

VQ="720"
LANG="ja"

#help
HELP_S="-h"
HELP_L="--help"

#YouTube EN
YT_EN_S="-e"
YT_EN_L="--yt${VQ}en"
YT_EN_CODE="136+(m4a[language=en-US]/m4a[language=en])"
#YouTube
YT_S="-y"
YT_L="--yt${VQ}"
YT_CODE="136+(140/m4a[language=${LANG}]/m4a)"

#universal
UNI_S="-u"
UNI_L="--uni${VQ}"
UNI_CODE="b[height<=${VQ}]/bv[height<=${VQ}]+ba"

#mp4
MP4_S="-m"
MP4_L="--mp4-${VQ}"
MP4_CODE="b[ext=mp4][height<=${VQ}]/bv[ext=mp4][height<=${VQ}]+(m4a/ba[ext=mp4]/ba)"

run ()
{
    local format_code

    yt-dlp "$1" -F
    #yt-dlp "$1" -Fv
    #yt-dlp "$1" -F --extractor-args youtube:player_client=all
    
    #print_help
    read -r -p "FORMAT_CODE:" format_code

    case "${format_code}" in
        "")
            return
        ;;
        "${HELP_S}" | "${HELP_L}")
            print_help
            pause
            return
        ;;
        "${YT_S}" | "${YT_L}")
            format_code="${YT_CODE}"
        ;;
        "${YT_EN_S}" | "${YT_EN_L}")
            format_code="${YT_EN_CODE}"
        ;;
        "${UNI_S}" | "${UNI_L}")
            format_code="${UNI_CODE}"
        ;;
        "${MP4_S}" | "${MP4_L}")
            format_code="${MP4_CODE}"
        ;;
    esac
        
    yt-dlp "$1" -f "${format_code}"
    #yt-dlp "$1" -f "${format_code}" --get-format
    pause
}

print_help()
{
    echo "Shortcuts:"
    print_sc "${HELP_S}" "${HELP_L}" "show this help message and exit"
    print_sc "${YT_S}" "${YT_L}" "${VQ}p with audio (YouTube)"
    print_sc "${YT_EN_S}" "${YT_EN_L}" "${VQ}p with English audio (YouTube)"
    print_sc "${MP4_S}" "${MP4_L}" "${VQ}p or lower with audio (mp4)"
    print_sc "${UNI_S}" "${UNI_L}" "${VQ}p or lower with audio (universal)"
}
print_sc()
{
    print_msg "${1}, ${2}" "${3}"
}
print_msg()
{
    printf '  %-15s%s\n' "${1}" "${2}"
}

pause()
{
    read -r -p "PRESS_ENTER:" answer
}

run "$1"